CREATE TABLE etl_staging_01_historico_consumo (
  id BIGSERIAL PRIMARY KEY,
  id_curral TEXT NOT NULL,
  lote TEXT,
  data DATE NOT NULL,
  qtd_animais INTEGER,
  dias_confinamento INTEGER,
  data_entrada DATE,
  leitura_cocho TEXT,
  ajuste_kg NUMERIC,
  leitura_noturna TEXT,
  sexo TEXT,
  grupo_genetico TEXT,
  peso_entrada_kg NUMERIC,
  peso_medio_estimado_kg NUMERIC,
  cms_previsto_kg NUMERIC,
  cms_realizado_kg NUMERIC,
  cmn_previsto_kg NUMERIC,
  cmn_realizado_kg NUMERIC,
  ms_dieta_meta_pc NUMERIC,
  ms_dieta_real_pc NUMERIC,
  cms_real_pc_pv NUMERIC,
  batch_id UUID DEFAULT gen_random_uuid(),
  uploaded_at TIMESTAMP DEFAULT NOW(),
  processed BOOLEAN DEFAULT FALSE
);