// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weqvnlbqnkjljiezjrqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlcXZubGJxbmtqbGppZXpqcnFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3OTk3MzQsImV4cCI6MjA2ODM3NTczNH0.BUkHzt1ZzRXTkAFwllJCjIBlowRBmKs4DELdX0K8p7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});